version: "3"

services:
  servak:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: my_dock
    tty: true
    
  nginx_server:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./aboba.sh:/aboba.sh
    ports:
     - "80:8080"
    depends_on:
     - servak
    container_name: nginx_server
    tty: true
    command: ["./aboba.sh"]
