version: "3"

services:
  servak:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: my_dock
    
  nginx_server:
    image: nginx
    container_name: nginx_server
    ports:
     - 80:8080
    depends_on:
     - servak
